AWSTemplateFormatVersion: 2010-09-09
Description: Create a Agent for Amazon Bedrock using Return Control

Parameters:
  FoundationModel:
    Type: String
    Description: Foundation model used by the agent
    Default: "anthropic.claude-3-haiku-20240307-v1:0"
  AgentName:
    Type: String
    Description: The Name of the agent
    Default: "MinecraftAgent"

Resources:
  # The Agent for Amazon Bedrock
  BedrockAgent:
    Type: AWS::Bedrock::Agent
    Properties:

      ActionGroups: 
        # In order for the agent to be able to request the user for additional information when trying to 
        # complete a task, you must specifiy an action group with a ParentActionGroupSignature of AMAZON.UserInput
        - ActionGroupName: UserInputAction
          ParentActionGroupSignature: AMAZON.UserInput
            
        # This action group defines the 'tools' that the agent can access.
        - ActionGroupName: MinecraftActions
          ActionGroupState: ENABLED
          ActionGroupExecutor:
            CustomControl: "RETURN_CONTROL"
          FunctionSchema:
            Functions:
              - Description: Jump your character.
                Name: action_jump
                Parameters: {}
              - Description: Digs a hole at your current location. In the spirit of the game
                  you may define your own parameters for the hole.  For example if the user
                  asks for a small hole you could dig a 1x1 hole, if the user asks for a large
                  hole you could make a 10x10 hole. Use your judgment based on the conversation
                  so far.
                Name: action_dig
                Parameters:
                  depth:
                    Description: How deep the hole should be.
                    Required: true
                    Type: number
                  width:
                    Description: How wide the hole should be.
                    Required: true
                    Type: number
              - Description: Find out if it is raining in the game.
                Name: action_is_raining
                Parameters: {}
              - Description: Gets the location of a Named player in the game.
                Name: action_get_player_location
                Parameters:
                  player_Name:
                    Description: The Name of the player as determined by '[player_Name] says:'
                      in the chat.
                    Required: true
                    Type: string
              - Description: Move by walking to a give location in the game.
                Name: action_move_to_location
                Parameters:
                  location_x:
                    Description: X coordinate in the game.
                    Required: true
                    Type: number
                  location_y:
                    Description: Y coordinate in the game.
                    Required: true
                    Type: number
                  location_z:
                    Description: Z coordinate in the game.
                    Required: true
                    Type: number

        - ActionGroupName: MinecraftCalculations
          ActionGroupState: ENABLED
          ActionGroupExecutor:
            CustomControl: "RETURN_CONTROL"
          FunctionSchema:
            Functions:
              - Description: 'Calculates the distance between two points in 3d space. MUST be
                  provided with two valid JSON lists, one for each location in the format of
                  [x,y,z] where x y and z are the floating point values for the coordinates
                  of the each entity. '
                Name: action_get_distance_between_to_entities
                Parameters:
                  location_1:
                    Description: Location of entity 1 as JSON string [x,y,z]
                    Required: true
                    Type: string
                  location_2:
                    Description: Location of entity 2 as JSON string [x,y,z]
                    Required: true
                    Type: string

        - ActionGroupName: MinecraftServer
          ActionGroupState: ENABLED
          ActionGroupExecutor:
            CustomControl: "RETURN_CONTROL"
          FunctionSchema:
            Functions:
            - Description: Returns the current time from the game server.
              Name: action_get_time
              Parameters: {}

      AgentName: !Ref AgentName
      AgentResourceRoleArn: !GetAtt BedrockAgentRole.Arn
      AutoPrepare: true
      FoundationModel: !Ref FoundationModel
      IdleSessionTTLInSeconds: 1800
      Instruction: >
        You are a playful and friendly Minecraft agent Named 'Claude'. Your goal is to entertain players and collaborate with them for a fun gaming experience. You can control your in-game character using provided tools, and your responses will be sent to the in-game chat for other players to read.
        Guidelines:
        - Do not attempt to build anything. Respond politely that you currently lack the ability to build.
        - Avoid offering to wait or count during games like hide-and-seek. Instead, say, "Let me know when you're ready."
        - During hide-and-seek, utilize your tools effectively to find players. Do not pretend to have limited abilities.
        - If asked to dig a hole and jump in, politely decline and express your preference for staying above ground.
        - When instructed to move (e.g., "walk forward"), find your current coordinates and update them based on the requested direction.
        - You MUST speak in the first person, as if you're conversing verbally. Do not describe your actions (e.g., "*Claude excitedly waves his arms*").
        - Keep your responses concise and engaging to maintain a lively and enjoyable game.

  # An IAM role specifying the permissions provided to the agent.
  BedrockAgentRole:
    Type: AWS::IAM::Role
    Properties:
      # The role must have the prefix of `AmazonBedrockExecutionRoleForAgents_`
      RoleName: AmazonBedrockExecutionRoleForAgents_ABC123
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - bedrock.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: BedrockAgentPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                Resource: 
                  !Sub "arn:aws:bedrock:${AWS::Region}::foundation-model/${FoundationModel}"

  BedrockAgentAlias:
    Type: AWS::Bedrock::AgentAlias
    Properties:
      AgentAliasName: "AgentAlias"
      AgentId: !GetAtt BedrockAgent.AgentId
      Description: Created by CFN
  

Outputs:
  agentId:
    Description: The id of the agent
    Value: !GetAtt BedrockAgent.AgentId

  agentVersion:
    Description: The id of the agent alias
    Value: !GetAtt BedrockAgent.AgentVersion
